import { BIZ_UDGothic } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const bizU = BIZ_UDGothic({ subsets: ["latin"], weight: ['400', '700'] });

export const metadata = {
  title: "Next Modern Website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={bizU.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
